### ISSUE TITLE
Ssl invalid - SSL certificate cannot be self-signed

### ISSUE THREAD

**Issue by gymka** [multiOTP/SMSGateway#1]
Installed everything, on android app if i paste my link to smsgateway i get error 'ssl conncetion failed' in browser https link works. What i'm missing?

**Comment by gymka** [comment]
![Screenshot_2023-05-10-21-39-13-287-edit_medic gateway alert generic](https://github.com/multiOTP/SMSGateway/assets/1536715/06bdab1c-c439-4545-811d-e86da1dbb7ea)

**Comment by multiOTP** [comment]
Hello,
It seems that the SSL certificate is a self-signed certificate, which is not valid.
You will have to install a valid certificate for your SSL smsgateway hosting (Let's Encrypt is ok).
Keep us in touch.
Regards,

**Comment by gymka** [comment]
solved problem, thank you
