### ISSUE TITLE
How to send SMS without report (to avoid extra costs)

### ISSUE THREAD

**Issue by gymka** [multiOTP/SMSGateway#2]
hi, how i can disable sms report? i mean i need to send sms without report, just simple sms(sms with report = 0.1eur; sms without report =0.0eur) i didn't found any setting for that.

**Comment by multiOTP** [comment]
Hello,
Please report your request to https://github.com/medic/cht-gateway, which is the repository of the Android App.
There is actually no option in the API of the Android App for that.
Regards,

**Comment by gymka** [comment]
There is option. Solved: in sendTextMessage made last to arguments 'null' and recompiled, part of functionality broken. But i don't care, sms is sent. I don't need nothing more :)

**Comment by multiOTP** [comment]
Thanks for the feedback.
Regards
